/**
 * InputMonitor — detects user keyboard/mouse activity and Minecraft window focus.
 *
 * Spawns native/input-monitor as a persistent subprocess that monitors global
 * keyboard and mouse events via macOS CGEventTap. Classifies events as
 * bot-generated or user-generated by comparing timestamps with the bot's
 * last action time.
 *
 * Also polls Minecraft window focus state via AppleScript every 1 second.
 *
 * Emits:
 *   'user-input'   — user provided keyboard/mouse input (bot should yield)
 *   'user-idle'    — 2 seconds with no user input (bot can resume)
 *   'focus-lost'   — Minecraft lost window focus
 *   'focus-gained' — Minecraft regained window focus
 *
 * macOS-only. On other platforms, start() is a no-op and userActive/mcFocused
 * return safe defaults (false/true) so the bot operates normally.
 */

const EventEmitter = require('events');
const path = require('path');
const fs = require('fs');
const { spawn, execSync } = require('child_process');

const IDLE_TIMEOUT_MS = 2000;       // Resume bot after 2s of no user input
const BOT_ACTION_WINDOW_MS = 150;   // Events within 150ms of bot action are bot-generated
const FOCUS_POLL_INTERVAL_MS = 1000; // Check Minecraft focus every 1s

class InputMonitor extends EventEmitter {
  constructor() {
    super();
    this._proc = null;
    this._available = false;
    this._lastBotActionTime = 0;
    this._userActive = false;
    this._idleTimer = null;
    this._mcFocused = true;
    this._focusInterval = null;
    this._buffer = '';
    this._focusLostCount = 0;  // consecutive polls showing MC not focused
  }

  /** Whether the user is currently providing keyboard/mouse input. */
  get userActive() { return this._userActive; }

  /** Whether Minecraft is the focused (frontmost) window. */
  get mcFocused() { return this._mcFocused; }

  /**
   * Mark that the bot is about to send a keyboard/mouse action.
   * Call this BEFORE every nut-js keyboard/mouse operation so the monitor
   * can filter out bot-generated events.
   */
  markBotAction() {
    this._lastBotActionTime = Date.now();
  }

  /** Start the native event monitor and focus polling. */
  start() {
    if (process.platform !== 'darwin') {
      console.warn('[input-monitor] Only supported on macOS. Auto-yield disabled.');
      return;
    }

    this._startNativeMonitor();
    this._startFocusPolling();
  }

  /** Stop everything and clean up. */
  stop() {
    this._available = false;

    if (this._idleTimer) {
      clearTimeout(this._idleTimer);
      this._idleTimer = null;
    }

    if (this._focusInterval) {
      clearInterval(this._focusInterval);
      this._focusInterval = null;
    }

    if (this._proc) {
      try { this._proc.kill(); } catch (_) {}
      this._proc = null;
    }
  }

  // ── Native monitor subprocess ──

  _startNativeMonitor() {
    const binaryPath = path.join(__dirname, 'native', 'input-monitor');
    const sourcePath = binaryPath + '.c';

    // Auto-compile if binary doesn't exist
    if (!fs.existsSync(binaryPath)) {
      if (!fs.existsSync(sourcePath)) {
        console.warn('[input-monitor] Source not found:', sourcePath);
        return;
      }
      try {
        console.log('[input-monitor] Compiling native helper...');
        execSync(`cc -O2 -o "${binaryPath}" "${sourcePath}" -framework ApplicationServices`);
        console.log('[input-monitor] Compiled successfully.');
      } catch (e) {
        console.warn('[input-monitor] Could not compile:', e.message);
        return;
      }
    }

    this._proc = spawn(binaryPath, [], { stdio: ['ignore', 'pipe', 'pipe'] });

    this._proc.on('error', (err) => {
      console.warn('[input-monitor] Process error:', err.message);
      this._available = false;
    });

    this._proc.on('exit', (code) => {
      if (this._available) {
        console.warn('[input-monitor] Process exited with code', code);
      }
      this._available = false;
    });

    // Read timestamps from stdout (line-buffered)
    this._proc.stdout.on('data', (data) => {
      this._buffer += data.toString();
      const lines = this._buffer.split('\n');
      this._buffer = lines.pop(); // Keep incomplete last line

      for (const line of lines) {
        const ts = parseInt(line.trim(), 10);
        if (isNaN(ts)) continue;
        this._onEvent(ts);
      }
    });

    // Log stderr (info/errors from native binary)
    this._proc.stderr.on('data', (data) => {
      const msg = data.toString().trim();
      if (msg) console.log('[input-monitor]', msg);
    });

    this._available = true;
    console.log('[input-monitor] Native event monitor ready.');
  }

  _onEvent(eventTime) {
    // Filter out bot-generated events
    if (eventTime - this._lastBotActionTime < BOT_ACTION_WINDOW_MS) {
      return; // This is the bot's own keyboard/mouse action
    }

    // This is user input
    if (!this._userActive) {
      this._userActive = true;
      this.emit('user-input');
    }

    // Restart idle timer
    if (this._idleTimer) clearTimeout(this._idleTimer);
    this._idleTimer = setTimeout(() => {
      this._userActive = false;
      this._idleTimer = null;
      this.emit('user-idle');
    }, IDLE_TIMEOUT_MS);
  }

  // ── Focus polling ──

  _startFocusPolling() {
    // Initial check
    this._checkFocus();

    this._focusInterval = setInterval(() => {
      this._checkFocus();
    }, FOCUS_POLL_INTERVAL_MS);
  }

  _checkFocus() {
    try {
      const result = execSync(
        "osascript -e 'tell application \"System Events\" to get name of first application process whose frontmost is true'",
        { timeout: 2000 }
      ).toString().trim().toLowerCase();

      const isMcFocused = result.includes('java') || result.includes('minecraft');

      if (isMcFocused) {
        this._focusLostCount = 0;  // reset consecutive miss counter
        if (!this._mcFocused) {
          this._mcFocused = true;
          console.log('[input-monitor] Minecraft gained focus.');
          this.emit('focus-gained');
        }
      } else {
        // Require 2 consecutive polls showing MC not focused before declaring
        // focus lost. Single-poll misses are often transient (osascript timing,
        // brief system UI popups) and cause false-positive refocus cycles that
        // open the game menu.
        this._focusLostCount++;
        if (this._focusLostCount >= 2 && this._mcFocused) {
          this._mcFocused = false;
          console.log('[input-monitor] Minecraft lost focus.');
          this.emit('focus-lost');
        }
      }
    } catch (_) {
      // AppleScript failed — assume unchanged
    }
  }
}

module.exports = { InputMonitor };
